/********************************************************************************
* ApiGatewayHttpApiV2Router.cs                                                  *
*                                                                               *
* Author: Denes Solti                                                           *
********************************************************************************/
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

using Amazon.Lambda.APIGatewayEvents;

namespace NanoRoute.AwsLambda
{
    using Json;

    /// <summary>
    /// Routes API Gateway HTTP API and Lambda Function URL <see cref="APIGatewayHttpApiV2ProxyRequest"/> instances through a NanoRoute pipeline.
    /// </summary>
    public sealed class ApiGatewayHttpApiV2Router : Router
    {
        private ApiGatewayHttpApiV2Router(RouterBuilder<ApiGatewayHttpApiV2Router, AwsLambdaRouterConfig> builder) : base(builder, builder.RouterConfig)
        {
        }

        /// <summary>
        /// Routes an API Gateway HTTP API or Lambda Function URL payload-format-2.0 request and returns the corresponding proxy response.
        /// </summary>
        /// <param name="request">The API Gateway v2 request event.</param>
        /// <param name="services">The service provider exposed to handlers through <see cref="RequestContext.Services"/>.</param>
        /// <param name="remainingTime">The time left before the Lambda invocation times out. Expired execution produces a response with <see cref="HttpStatusCode.GatewayTimeout"/> status.</param>
        /// <returns>The API Gateway v2 proxy response generated by NanoRoute.</returns>
        public async Task<APIGatewayHttpApiV2ProxyResponse> Route(APIGatewayHttpApiV2ProxyRequest request, IServiceProvider services, TimeSpan remainingTime)
        {
            Ensure.NotNull(request, nameof(request));
            Ensure.NotNull(services, nameof(services));

            TimeSpan cancellationDelay = remainingTime.Add(TimeSpan.FromSeconds(-1));
            if (cancellationDelay <= TimeSpan.Zero)
                return Timeout();

            using CancellationTokenSource cts = new();
            cts.CancelAfter(cancellationDelay);

            using HttpRequestMessage requestMessage = request.CreateRequestMessage();

            try
            {
                using HttpResponseMessage responseMessage = await Handle(requestMessage, services, cts.Token);

                return await responseMessage.CreateResponse();
            }
            catch (OperationCanceledException)
            {
                return Timeout();
            }

            APIGatewayHttpApiV2ProxyResponse Timeout() => new()
            {
                StatusCode = (int) HttpStatusCode.GatewayTimeout,
                Body = JsonSerializer.Serialize
                (
                    new ErrorDetails
                    {
                        Status = HttpStatusCode.GatewayTimeout,
                        Title = "Gateway Timeout",
                        TraceId = request.RequestContext.RequestId
                    },
                    ErrorDetails.JsonTypeInfo
                ),
                Headers = new Dictionary<string, string>
                {
                    ["Content-Type"] = "application/json"
                }
            };
        }

        /// <summary>
        /// Creates a strongly typed builder for configuring an <see cref="ApiGatewayHttpApiV2Router"/>.
        /// </summary>
        /// <returns>A builder that can register handlers, value parsers, and router configuration.</returns>
        public static RouterBuilder<ApiGatewayHttpApiV2Router, AwsLambdaRouterConfig> CreateBuilder() => new RouterBuilder<ApiGatewayHttpApiV2Router, AwsLambdaRouterConfig>(static builder => new ApiGatewayHttpApiV2Router(builder));
    }
}
