/********************************************************************************
* ApiGatewayV2Router.cs                                                         *
*                                                                               *
* Author: Denes Solti                                                           *
********************************************************************************/
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

using Amazon.Lambda.APIGatewayEvents;
using Amazon.Lambda.Core;

namespace NanoRoute.AwsLambda
{
    /// <summary>
    /// Routes API Gateway HTTP API and Lambda Function URL <see cref="APIGatewayHttpApiV2ProxyRequest"/> instances through a NanoRoute pipeline.
    /// </summary>
    /// <example>
    /// <code>
    /// ApiGatewayV2Router router = ApiGatewayV2Router
    ///     .CreateBuilder()
    ///     .AddJsonErrorDetails()
    ///     .AddDefaultValueParsers()
    ///     .AddHandler("GET", "/health/", (context, _) =&gt; HttpResponseMessage.Json(new { status = "ok" }))
    ///     .CreateRouter();
    /// </code>
    /// </example>
    public sealed class ApiGatewayV2Router : RouterBase<ApiGatewayV2RouterConfig>
    {
        private ApiGatewayV2Router(RouterBuilder<ApiGatewayV2Router, ApiGatewayV2RouterConfig> builder) : base(builder, builder.RouterConfig)
        {
        }

        /// <summary>
        /// Creates a strongly typed builder for <see cref="ApiGatewayV2Router"/>.
        /// </summary>
        /// <returns>A builder that can register handlers, value parsers, and router configuration.</returns>
        /// <example>
        /// <code>
        /// RouterBuilder&lt;ApiGatewayV2Router, ApiGatewayV2RouterConfig&gt; builder = ApiGatewayV2Router.CreateBuilder();
        /// </code>
        /// </example>
        public static RouterBuilder<ApiGatewayV2Router, ApiGatewayV2RouterConfig> CreateBuilder() => new(static builder => new ApiGatewayV2Router(builder));

        /// <summary>
        /// Routes an API Gateway HTTP API or Lambda Function URL payload-format-2.0 request and returns the corresponding proxy response.
        /// </summary>
        /// <param name="request">The API Gateway v2 request event.</param>
        /// <param name="services">The service provider exposed to handlers through <see cref="RequestContext.Services"/>.</param>
        /// <param name="context">
        /// The Lambda invocation context used to derive the cancellation deadline from <see cref="ILambdaContext.RemainingTime"/>.
        /// </param>
        /// <returns>The API Gateway v2 proxy response generated by NanoRoute.</returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="request"/>, <paramref name="services"/>, or <paramref name="context"/> is
        /// <see langword="null"/>.
        /// </exception>
        /// <exception cref="InvalidOperationException">Thrown when the request uses an unsupported HTTP method.</exception>
        /// <exception cref="InvalidOperationException">Thrown when the API Gateway request does not contain a recognizable URI.</exception>
        /// <exception cref="HttpRequestException">
        /// Thrown when no handler matches the request path or a matched handler signals an HTTP failure that is not
        /// translated by middleware.
        /// </exception>
        /// <example>
        /// <code>
        /// APIGatewayHttpApiV2ProxyResponse response = await router.Route(request, services, context);
        /// </code>
        /// </example>
        public async Task<APIGatewayHttpApiV2ProxyResponse> Route(APIGatewayHttpApiV2ProxyRequest request, IServiceProvider services, ILambdaContext context)
        {
            ArgumentNullException.ThrowIfNull(request);
            ArgumentNullException.ThrowIfNull(services);
            ArgumentNullException.ThrowIfNull(context);

            TimeSpan cancellationDelay = context.RemainingTime - Config.LambdaTimeoutBuffer;
            if (cancellationDelay <= TimeSpan.Zero)
                return Timeout();

            using CancellationTokenSource cts = new();
            cts.CancelAfter(cancellationDelay);

            using HttpRequestMessage requestMessage = request.CreateRequestMessage();

            try
            {
                using HttpResponseMessage responseMessage = await Route(requestMessage, services, cts.Token).ConfigureAwait(false);

                return await responseMessage.CreateResponse().ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                return Timeout();
            }

            APIGatewayHttpApiV2ProxyResponse Timeout() => new()
            {
                StatusCode = (int) HttpStatusCode.GatewayTimeout,
                Body = JsonSerializer.Serialize
                (
                    new ErrorDetails
                    {
                        Status = HttpStatusCode.GatewayTimeout,
                        Title = "Gateway Timeout",
                        TraceId = request.RequestContext.RequestId
                    },
                    ErrorDetails.JsonTypeInfo
                ),
                Headers = new Dictionary<string, string>
                {
                    ["Content-Type"] = "application/json"
                }
            };
        }
    }
}
