/********************************************************************************
* ApiGatewayHttpApiV2Router.cs                                                  *
*                                                                               *
* Author: Denes Solti                                                           *
********************************************************************************/
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

using Amazon.Lambda.APIGatewayEvents;

namespace NanoRoute.AwsLambda
{
    /// <summary>
    /// Routes <see cref="APIGatewayHttpApiV2ProxyRequest"/> instances through a NanoRoute pipeline.
    /// </summary>
    public sealed class ApiGatewayHttpApiV2Router : Router
    {
        private ApiGatewayHttpApiV2Router(RouterBuilder<ApiGatewayHttpApiV2Router, AwsLambdaRouterConfig> builder) : base(builder, builder.RouterConfig)
        {
        }

        /// <summary>
        /// Routes a Lambda HTTP API payload-format-2.0 request and returns the corresponding proxy response.
        /// </summary>
        /// <param name="request">The API Gateway v2 request event.</param>
        /// <param name="services">The service provider exposed to handlers through <see cref="RequestContext.Services"/>.</param>
        /// <returns>The API Gateway v2 proxy response generated by NanoRoute.</returns>
        public async Task<APIGatewayHttpApiV2ProxyResponse> Route(APIGatewayHttpApiV2ProxyRequest request, IServiceProvider services)
        {
            Ensure.NotNull(request, nameof(request));
            Ensure.NotNull(services, nameof(services));

            using HttpRequestMessage requestMessage = request.CreateRequestMessage();
            using HttpResponseMessage responseMessage = await Handle(requestMessage, services, CancellationToken.None);

            return await responseMessage.CreateResponse();
        }

        /// <summary>
        /// Creates a strongly typed builder for configuring an <see cref="ApiGatewayHttpApiV2Router"/>.
        /// </summary>
        /// <returns>A builder that can register handlers, value parsers, and router configuration.</returns>
        public static RouterBuilder<ApiGatewayHttpApiV2Router, AwsLambdaRouterConfig> CreateBuilder() => new(static builder => new ApiGatewayHttpApiV2Router(builder));
    }
}
