<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <Description>HttpListener adapter for NanoRoute.</Description>
    <Version>1.0.0-preview1</Version>
    <PackageTags>$(PackageTags);HttpListener</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NanoRoute\NanoRoute.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>NanoRoute.Perf</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute" Condition="'$(Configuration)'=='Debug'">
      <_Parameter1>NanoRoute.HttpListener.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
