//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoRoute.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoRoute.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported content type..
        /// </summary>
        internal static string ERR_BAD_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("ERR_BAD_CONTENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request..
        /// </summary>
        internal static string ERR_BAD_REQUEST {
            get {
                return ResourceManager.GetString("ERR_BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding failed..
        /// </summary>
        internal static string ERR_DECODING_FAILED {
            get {
                return ResourceManager.GetString("ERR_DECODING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        internal static string ERR_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("ERR_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments for &apos;{0}&apos; at offset {1}..
        /// </summary>
        internal static string ERR_INVALID_ARGUMENTS {
            get {
                return ResourceManager.GetString("ERR_INVALID_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parser arguments..
        /// </summary>
        internal static string ERR_INVALID_PARSERS_ARGS {
            get {
                return ResourceManager.GetString("ERR_INVALID_PARSERS_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pattern at offset {0}..
        /// </summary>
        internal static string ERR_INVALID_PATTERN {
            get {
                return ResourceManager.GetString("ERR_INVALID_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query bindings..
        /// </summary>
        internal static string ERR_INVALID_QUERY_BINDINGS {
            get {
                return ResourceManager.GetString("ERR_INVALID_QUERY_BINDINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verb: {0}.
        /// </summary>
        internal static string ERR_INVALID_VERB {
            get {
                return ResourceManager.GetString("ERR_INVALID_VERB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not allowed..
        /// </summary>
        internal static string ERR_METHOD_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERR_METHOD_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter: {0}.
        /// </summary>
        internal static string ERR_MISSING_REQUIRED_PARAMETER {
            get {
                return ResourceManager.GetString("ERR_MISSING_REQUIRED_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value parser is registered for &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_NO_SUCH_PARSER {
            get {
                return ResourceManager.GetString("ERR_NO_SUCH_PARSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        internal static string ERR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only prefix patterns are allowed..
        /// </summary>
        internal static string ERR_NOT_PREFIX {
            get {
                return ResourceManager.GetString("ERR_NOT_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional parameters are not supported in segment definitions..
        /// </summary>
        internal static string ERR_OPTIONAL_PARAMETERS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_OPTIONAL_PARAMETERS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting parameter names are not allowed for the same route segment..
        /// </summary>
        internal static string ERR_PARAMETER_OVERRIDE {
            get {
                return ResourceManager.GetString("ERR_PARAMETER_OVERRIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate query parameter: {0}.
        /// </summary>
        internal static string ERR_QUERY_DUPLICATE_PARAMETER {
            get {
                return ResourceManager.GetString("ERR_QUERY_DUPLICATE_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query parameter: {0}.
        /// </summary>
        internal static string ERR_QUERY_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("ERR_QUERY_INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing query parameters: {0}.
        /// </summary>
        internal static string ERR_QUERY_MISSING_PARAMETER {
            get {
                return ResourceManager.GetString("ERR_QUERY_MISSING_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped value sources cannot have a binding name..
        /// </summary>
        internal static string ERR_SKIPPED_VALUE_SOURCE_NAME {
            get {
                return ResourceManager.GetString("ERR_SKIPPED_VALUE_SOURCE_NAME", resourceCulture);
            }
        }
    }
}
