#############################################################################
#                                                                           #
# master.yml                                                                #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################
name: Run tests and publish artifacts

on:
  push:
    branches: 
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  POWERSHELL_TELEMETRY_OPTOUT: true

jobs:
  tests-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # .NET Framework is part of the windows images
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
             3.1.x
             10.0.x

      - name: Run tests
        shell: pwsh
        run: ./Scripts/Run-Tests.ps1

      - name: Create badges directory
        shell: pwsh
        run: New-Item -ItemType Directory -Path ./Artifacts/badges -Force | Out-Null

      - name: Parse test results
        id: tests
        shell: pwsh
        run: |
          $results = ([xml](Get-Content ./Artifacts/NanoRoute.Tests.Results.xml)).testsuites.ChildNodes[0]
          "passed=$($results.tests)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "skipped=$($results.skipped)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          if ($results.skipped -gt 0) { "color=yellow"| Out-File -FilePath $env:GITHUB_OUTPUT -Append }
          else { "color=green" | Out-File -FilePath $env:GITHUB_OUTPUT -Append }

      - name: Create tests badge
        uses: emibcn/badge-action@v2
        with:
          label: tests
          status: "Passed: ${{ steps.tests.outputs.passed }}, Skipped: ${{ steps.tests.outputs.skipped }}"
          color: ${{ steps.tests.outputs.color }}
          path: ./Artifacts/badges/tests-badge.svg

      - name: Parse coverage
        id: coverage
        shell: pwsh
        run: |
          $matches = [regex]::Match((Get-Content -Raw ./Artifacts/CoverageReport/Index.html), '<div\s+class="[^"]*\bcardpercentagebar\b[^"]*">\s*([^<]+)\s*</div>')
          $coveragePercent = [int]($matches.Groups[1].Value  -replace '%','')
          "value=$coveragePercent" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          if ($coveragePercent -lt 60) { "color=red"| Out-File -FilePath $env:GITHUB_OUTPUT -Append }
          elseif ($coveragePercent -lt 80) { "color=yellow"| Out-File -FilePath $env:GITHUB_OUTPUT -Append }
          else { "color=green"| Out-File -FilePath $env:GITHUB_OUTPUT -Append }
          
      - name: Create coverage badge
        uses: emibcn/badge-action@v2
        with:
          label: coverage
          status: ${{ steps.coverage.outputs.value }}%
          color: ${{ steps.coverage.outputs.color }}
          path: ./Artifacts/badges/coverage-badge.svg

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: ./Artifacts

  create-api-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Generate API docs
        shell: pwsh
        run: ./Scripts/Build-Docs.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: docs
          path: ./Artifacts/docs

  upload-artifacts:
    needs:
      - tests-windows
      - create-api-docs
    runs-on: windows-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: Download results
        run: gh run download ${{ github.run_id }} --repo ${{ github.repository }} --dir Artifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifacts to gh-pages
        shell: pwsh
        run: |
          ./Scripts/Update-GitHubPages.ps1 {
            param($ROOT, $GH_PAGES)

            $badges = Join-Path $GH_PAGES "badges"
            if (-not (Test-Path $badges)) { throw "Badges directory not found: $badges" }

            Remove-Item -Path (Join-Path $badges "*.svg") -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path (Join-Path $ROOT "Artifacts") -Recurse -Filter *-badge.svg -File | ForEach-Object {
              Copy-Item -Path $_.FullName -Destination $badges -Force
            }

            Remove-Item -Path (Join-Path $GH_PAGES "CoverageReport") -Recurse -Force -ErrorAction SilentlyContinue
            Move-Item (Join-Path $ROOT "Artifacts/test-results/CoverageReport") $GH_PAGES

            Remove-Item -Path (Join-Path $GH_PAGES "docs") -Recurse -Force -ErrorAction SilentlyContinue
            Move-Item (Join-Path $ROOT "Artifacts/docs") $GH_PAGES
          } "${{ secrets.GITHUB_TOKEN }}"
